# Generated by Django 3.2.5 on 2024-06-19 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('ToBeDone', 'To Be Done'), ('InProgress', 'In Progress'), ('InReview', 'In Review'), ('InTesting', 'In Testing'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Backlog', max_length=50, verbose_name='Status')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('main_character', models.CharField(choices=[('SupportAgent', 'Support Agent'), ('PropertyManager', 'Property Manager'), ('Client', 'Client'), ('Developer', 'Developer')], default='SupportAgent', max_length=50, verbose_name='Main Character')),
                ('story', models.TextField(verbose_name='Story')),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('ToBeDone', 'To Be Done'), ('InProgress', 'In Progress'), ('InReview', 'In Review'), ('InTesting', 'In Testing'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Backlog', max_length=50, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('ToBeDone', 'To Be Done'), ('InProgress', 'In Progress'), ('InReview', 'In Review'), ('InTesting', 'In Testing'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Backlog', max_length=50, verbose_name='Status')),
                ('section_type', models.CharField(choices=[('Chapter', 'Chapter'), ('Section', 'Section'), ('Subsection', 'Subsection')], max_length=50, verbose_name='Section Type')),
                ('jira_design_tickets', models.CharField(max_length=100, unique=True, verbose_name='Jira Design Tickets')),
                ('jira_developer_tickets', models.CharField(max_length=100, unique=True, verbose_name='Jira Developer Tickets')),
                ('jira_test_tickets', models.CharField(max_length=100, unique=True, verbose_name='Jira Test Tickets')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job', verbose_name='Job')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_reference', to='jobs.acceptancecriteria', verbose_name='Parent')),
                ('sibling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling_reference', to='jobs.acceptancecriteria', verbose_name='Sibling')),
            ],
            options={
                'verbose_name': 'Acceptance Criteria',
                'verbose_name_plural': 'Acceptance Criteria',
                'db_table': 'acceptance_criteria',
            },
        ),
    ]
